export const FETCH_DASHBOARD_STATS_START = 'FETCH_DASHBOARD_STATS_START';
export const FETCH_DASHBOARD_STATS_SUCCESS = 'FETCH_DASHBOARD_STATS_SUCCESS';
export const FETCH_DASHBOARD_STATS_FAILURE = 'FETCH_DASHBOARD_STATS_FAILURE';
export const FETCH_DASHBOARD_TRANSACTION_START =
  'FETCH_DASHBOARD_TRANSACTION_START';
export const FETCH_DASHBOARD_TRANSACTION_SUCCESS =
  'FETCH_DASHBOARD_TRANSACTION_SUCCESS';
export const FETCH_DASHBOARD_TRANSACTION_FAILURE =
  'FETCH_DASHBOARD_TRANSACTION_FAILURE';

export const TRANSFER_CASH_START = 'TRANSFER_CASH_FAILURE';
export const TRANSFER_CASH_SUCCESS = 'TRANSFER_CASH_SUCCESS';
export const TRANSFER_CASH_FAILURE = 'TRANSFER_CASH_FAILURE';
